14-Trees-Foundation/14trees-web-monorepo

apps/api/src/controllers/appV2TreesController.js, apps/api/src/controllers/helper/roles.js, apps/api/src/controllers/helper/uploadtos3AppV2.js, apps/api/src/helpers/utilsAppV2.js, apps/api/src/models/logs.js, apps/api/src/models/shifts.js, apps/api/src/models/user.ts, apps/api/src/routes/appV2Routes.js, apps/api/src/server.ts
added required routes for appv2 for our mern code.
=> added required routes for appv2

apps/api/src/controllers/donationsController.ts, apps/api/src/repo/donationsRepo.ts, apps/api/src/routes/donationRoutes.ts
Donation Controller:
Added auto reserve to correctly reserve individually selected Trees 
Donation Repo:
Added function to filter according to plant type
Donation Routes:
Corrected the typo donations.reserveTreesForDonation to donations.unreserveTreesForDonation to unreserve trees
=> Donation Tree updates

apps/api/src/controllers/donationsController.ts, apps/api/src/repo/donationsRepo.ts, apps/api/src/routes/donationRoutes.ts
Implemented a controller function to handle donation email notifications that takes a donation_id, and sends a "Trees Planted" notification email to the sponsor/recipient/assignee
=> Donation Email Update

apps/api/src/controllers/donationsController.ts, apps/api/src/facade/donationService.ts, apps/api/src/repo/donationsRepo.ts, apps/api/src/routes/donationRoutes.ts
This backend function returns reservation statistics for a specific donation. It provides the following values:
- total_requested: The total number of trees requested for the donation_id.
- already_reserved: The number of trees that have already been reserved.
- remaining: The number of trees still available for reservation.
=> Function to send Reservation Stats

apps/api/src/models/tree.ts
Added model setters to convert null → [ ] for array fields (tags, memory_images, status_message) to prevent .map() errors in Sequelize.
=> Tree model Update

apps/api/src/controllers/giftCardController.ts, apps/api/src/models/gift_card_request.ts, apps/api/src/routes/giftCardRoutes.ts
Controller changes to handle Csv and logo
=> Changes for csv and logo

apps/front-page/app/donate/page.tsx, apps/front-page/app/gift-trees/page.tsx, apps/front-page/app/giftTrees/page.tsx, apps/front-page/components/NavHeader.tsx, apps/front-page/src/api/apiClient.ts, apps/front-page/src/utils.ts
Created a new Gift Trees Form page
=> New Gift Trees form  page

apps/api/src/repo/treesSnapshotsRepo.ts, apps/api/src/services/cron.ts
- Agg. Audit Report: Fetches summarized audit data (staff name, date, and total trees audited) 
- Plot Audit Report: Retrieves  (plot ID, name, sapling ID, and audit date)
=> Cron update for Audit report

apps/api/src/controllers/helper/giftRequestHelper.ts, apps/api/src/models/gift_card_request.ts
- Add mail_sent boolean field to GiftCardRequest model to track email delivery status
- Update sendMailsToSponsors to mark mail_sent=true on successful email sends.
=> Email Status Update

apps/front-page/app/donate/donationSummary.tsx, apps/front-page/app/donate/page.tsx, apps/front-page/components/donate/UserDetailsForm.tsx, apps/front-page/components/donate/UserFormField.tsx, apps/front-page/src/api/apiClient.ts
Updated Fields in doantion Form page
=> Donation Form 

apps/front-page/app/gift-trees/page.tsx
Removed Tree planting Options
For Payment 
- if amount is above limit show bank transfer otherwise show razorpay option
Remove Tax Benefits field and keep Indian Citizen default option
Moved Your details section at the bottom of the Form
=> New fields in Gifting Form page

apps/front-page/app/gift-trees/page.tsx
Modified the Gifting form page
=> Gift Form Page updates

apps/front-page/app/donate/donationSummary.tsx, apps/front-page/app/donate/page.tsx, apps/front-page/app/gift-trees/giftingSummary.tsx, apps/front-page/app/gift-trees/page.tsx, apps/front-page/components/NavHeader.tsx, apps/front-page/components/Recipient.tsx, apps/front-page/components/Recipients.tsx, apps/front-page/components/gift-trees/GiftCardPreview.tsx
Added new Summary page  and changed fields for Giting form
=> New Fileds and summary page for Gifting form

apps/api/src/controllers/donationsController.ts, apps/api/src/facade/donationService.ts, apps/api/src/services/google.ts
Created a new insertDonationIntoGoogleSheet function
to insert donation form data into google spreadsheet
=> Donation Form Spreadsheet

apps/api/src/controllers/donationsController.ts, apps/api/src/facade/donationService.ts, apps/api/src/services/gmail/templates/backoffice_donation.html
Created new function sendDonationNotificationToBackOffice to send Email to backoffice when a donation is created
=> New Function to send Donation email to Backoffice

apps/front-page/app/gift-trees/page.tsx, apps/front-page/components/gift-trees/GiftCardPreview.tsx
Added New Gift Card messages for 
- Wedding
- Wedding Anniversary 
- Festival Celebration
=> Added new Gift card Messages

apps/api/src/services/gmail/templates/receiver-multi-trees-anniversary.html, apps/api/src/services/gmail/templates/receiver-multi-trees-wedding.html, apps/api/src/services/gmail/templates/receiver-single-tree-anniversary.html, apps/api/src/services/gmail/templates/receiver-single-tree-wedding.html, apps/api/src/services/gmail/templates/sponsor-multi-trees-anniversary.html, apps/api/src/services/gmail/templates/sponsor-multi-trees-wedding.html, apps/api/src/services/gmail/templates/sponsor-single-tree-anniversary.html, apps/api/src/services/gmail/templates/sponsor-single-tree-wedding.html
=> New Email templates for Wedding and Anniversary

apps/api/src/facade/giftCardsService.ts, apps/api/src/models/gift_card_request.ts, apps/api/src/repo/giftCardsRepo.ts, apps/api/src/server.ts, apps/api/src/services/cron.ts, apps/api/src/services/gmail/templates/backoffice_gifting.html, apps/api/src/services/gmail/templates/gifting-accounts.html, apps/api/src/services/gmail/templates/gifting-csr.html, apps/api/src/services/gmail/templates/gifting-volunteer.html
Created 4 new functions
- sendGiftingNotificationToBackOffice
- sendGiftingNotificationToAccounts
- sendGiftingNotificationForVolunteers
- sendGiftingNotificationForCSR
=> New Gift card service mail functions

apps/api/src/controllers/treesController.ts, apps/api/src/repo/userRepo.ts, apps/api/src/routes/treeRoutes.ts
Created new getMappedTreesForGroup function
=> New Tree Mapping Function for Group

apps/front-page/app/gift-trees/giftingSummary.tsx, apps/front-page/app/gift-trees/page.tsx, apps/front-page/components/gift-trees/GiftCardPreview.tsx
=> Gifting Form updates

apps/front-page/app/donate/page.tsx, apps/front-page/app/gift-trees/page.tsx, apps/front-page/components/Recipient.tsx, apps/front-page/components/Recipients.tsx
Updated Donation and Gifting Form Pages
=> Updated Forms

apps/api/src/controllers/campaignController.ts, apps/api/src/repo/campaignsRepo.ts, apps/api/src/routes/campaignRoutes.ts
Updated campaign Functions for Admin Dasboard
=> Campaign Controller functions

apps/api/src/controllers/giftCardController.ts
Cloned request will get a new album ID when created.
=> Fixed album_id issue

apps/front-page/app/plant-memory/giftingSummary.tsx, apps/front-page/app/plant-memory/page.tsx, apps/front-page/components/CsvUpload.tsx, apps/front-page/components/Recipient.tsx, apps/front-page/components/Recipients.tsx
=> Csv component for gifting Form

apps/api/src/controllers/giftCardController.ts, apps/api/src/facade/donationService.ts, apps/api/src/facade/giftCardsService.ts, apps/api/src/services/gmail/templates/backoffice_donation.html, apps/api/src/services/gmail/templates/backoffice_gifting.html, apps/api/src/services/gmail/templates/donation-accounts.html, apps/api/src/services/gmail/templates/donation-csr.html, apps/api/src/services/gmail/templates/donation-volunteer.html, apps/api/src/services/gmail/templates/gifting-accounts.html, apps/api/src/services/gmail/templates/gifting-csr.html, apps/api/src/services/gmail/templates/gifting-volunteer.html
=> Added pan details to Email

apps/api/src/controllers/viewPermissionsController.ts, apps/api/src/routes/viewRoutes.ts
Created New Controller funtions to add and delete viewusers
=> New Add/Delete View User Function
